paginate = 40
defaultContentLanguage = 'en'
showLanguageSelector = true
defaultContentLanguageInSubdir = false
baseURL = '/'

disableKinds = ["taxonomyTerm","sitemap","RSS"]

[params]
[sitemap]
filename = 'static-content/sitemap.xml'


[languages]
[languages.en]
  contentDir = 'content/en'
  languageName = "EN"
  weight=1
  title = "AsgardPvP"
  owner = "Progon & Holy"
  description = "Diablo 2 Asgard PvP Realm is an international Diablo 2 PvP arena server designed to play PvP/Duels"
  keywords = "diablo 2 asgard, diablo 2 asgardpvp"
  copyright = "Progon & Holy"

[languages.ru]
  contentDir = 'content/ru'
  languageName = "RU"
  weight=2
  title = "АсгардПвП"
  owner = "Progon & Holy"
  description = "Диабло 2 Асгард ПвП это международный Диабло 2 ПвП сервер"
  keywords = "диабло 2 асгард, диабло 2 асгардпвп"
  copyright = "Progon & Holy"

[languages.en.menu]
  [[languages.en.menu.main]]
        identifier = "home"
        name = "Home page"
        pageref= "/"
        weight = 1

  [[languages.en.menu.main]]
        identifier = "connect"
        name = "How to connect"
        pageref= "/how-to-connect"
        weight = 2

  [[languages.en.menu.main]]
        identifier = "reg"
        name = "Create account"
        pageref= "/create-account"
        weight = 3

  [[languages.en.menu.main]]
        identifier = "mod"
        name = "Mod info"
        pageref= "/mod-info"
        weight = 4

  [[languages.en.menu.main]]
        identifier = "recipes"
        name = "Cube recipes"
        pageref= "/cube-recipes"
        weight = 5

  [[languages.en.menu.main]]
        identifier = "gm"
        name = "GM"
        pageref= "/gm-rules"
        weight = 6

  [[languages.en.menu.main]]
        identifier = "fpk"
        name = "FPK"
        pageref= "/fpk-rules"
        weight = 7

  [[languages.en.menu.main]]
        identifier = "/guides"
        name = "Guides"
        pageref= "/guides/"
        weight = 8
        description = "Diablo 2 Asgard PvP Realm Guides"
        keywords = "diablo guides, d2 guides"

  [[languages.en.menu.main]]
        identifier = "contacts"
        name = "Contacts"
        pageref= "/contacts"
        weight = 9


[languages.ru.menu]
  [[languages.ru.menu.main]]
        identifier = "home"
        name = "Главная"
        url = "/ru/"
        pageref= "/"
        weight = 1
  [[languages.ru.menu.main]]
        identifier = "connect"
        name = "Как присоедениться"
        url = "/ru/how-to-connect"
        pageref= "/how-to-connect"
        weight = 2

  [[languages.ru.menu.main]]
        identifier = "reg"
        name = "Создать аккаунт"
        url = "/ru/create-account"
        pageref= "create-account"
        weight = 3

  [[languages.ru.menu.main]]
        identifier = "mod"
        name = "Мод"
        url = "/ru/mod-info"
        pageref= "mod-info"
        weight = 4

  [[languages.ru.menu.main]]
        identifier = "recipes"
        name = "Рецепты"
        url = "/ru/cube-recipes"
        pageref= "cube-recipes"
        weight = 5

  [[languages.ru.menu.main]]
        identifier = "gm"
        name = "ГМ"
        url = "/ru/gm-rules"
        pageref= "gm-rules"
        weight = 6

  [[languages.ru.menu.main]]
        identifier = "fpk"
        name = "ФПК"
        url = "/ru/fpk-rules"
        pageref= "fpk-rules"
        weight = 7

  [[languages.ru.menu.main]]
        identifier = "guides"
        name = "Гайды"
        url = "/ru/guides/"
        pageref= "guides/"
        weight = 8
        description = "Диабло 2 Асгард ПвП Гайды"
         keywords = "диабло 2 гайды, д2 гайды"

  [[languages.ru.menu.main]]
        identifier = "contacts"
        name = "Контакты"
        url = "/ru/contacts"
        pageref= "contacts"
        weight = 9


