baseurl = "/"
languageCode = "en-us"
paginate = 20

[params]

  showLanguageSelector = true
  defaultContentLanguageInSubdir = true

[languages]

  [languages.en]
    contentDir = 'content/en'
    baseURL = ''
    languageName = "English"
    weight=1
    title = "AsgardPvP"
    subtitle = "International Diablo 2 PvP/Duel server/realm"
    owner = "Progon & Holy"
    keywords = ""
    copyright = ""


  [languages.ru]
    contentDir = 'content/ru'
    baseURL = ''
    LanguageName = "Русский"
    weight=2
    title = "АсгардПвП"
    subtitle = "Международный Диабло 2 ПвП сервер"
    owner = "Progon & Holy"
    keywords = ""
    copyright = ""




    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "Home"
        name = "Home"

        weight = 1

      [[languages.en.menu.main]]
        identifier = "How to connect"
        name = "How to connect"
        url = "/how-to-connect"
        weight = 2

      [[languages.en.menu.main]]
        identifier = "Create account"
        name = "Create account"
        url = "/create-account"
        weight = 3

      [[languages.en.menu.main]]
        identifier = "Mod info"
        name = "Mod info"
        url = "/mod-info"
        weight = 4

      [[languages.en.menu.main]]
        identifier = "Cube recipes"
        name = "Cube recipes"
        url = "/cube-recipes"
        weight = 5

      [[languages.en.menu.main]]
        identifier = "GM Rules"
        name = "GM Rules"
        url = "/gm-rules"
        weight = 6

      [[languages.en.menu.main]]
        identifier = "FPK Rules"
        name = "FPK Rules"
        url = "/fpk-rules"
        weight = 7

      [[languages.en.menu.main]]
        identifier = "Guides"
        name = "Guides"
        url = "/guides/"
        weight = 8

      [[languages.en.menu.main]]
        identifier = "Contacts"
        name = "Contacts"
        url = "/contacts"
        weight = 9

  [languages.ru.params.logo]
      logoText = "AsgardPvP"
      logoHomeLink = ""

    [languages.ru.menu]
      [[languages.en.menu.main]]
        identifier = "Home"
        name = "Home"
        url = ""
        weight = 1