paginate = 40
defaultContentLanguage = 'en'
showLanguageSelector = true
defaultContentLanguageInSubdir = false
baseURL = '/'

disableKinds = ["taxonomy","sitemap","RSS"]

[params]
[sitemap]
filename = '/sitemap.xml'


[languages]
[languages.en]
  contentDir = 'content/en'
  languageName = "EN"
  weight=1
  title = "AsgardPvP"
  copyright = "Progon & Holy"
  [languages.en.params]
    keywords = "diablo 2 asgard, diablo 2 asgardpvp"
    owner = "Progon & Holy"
    description = "Diablo 2 Asgard PvP Realm is an international Diablo 2 PvP arena server designed to play PvP/Duels"
    
    

[languages.ru]
  contentDir = 'content/ru'
  languageName = "RU"
  weight=2
  title = "АсгардПвП"
  [languages.ru.params]
    keywords = "диабло 2 асгард, диабло 2 асгардпвп"
    owner = "Progon & Holy"
    description = "Диабло 2 Асгард ПвП это международный Диабло 2 ПвП сервер"
    copyright = "Progon & Holy"

[languages.en.menu]
  [[languages.en.menu.main]]
        identifier = "home"
        name = "Home page"
        pageRef= "/"
        weight = 1

  [[languages.en.menu.main]]
        identifier = "how"
        name = "How to connect"
        pageRef= "how-to-connect"
        weight = 2

  [[languages.en.menu.main]]
        identifier = "reg"
        name = "Create account"
        pageRef= "/create-account"
        weight = 3

  [[languages.en.menu.main]]
        identifier = "mod"
        name = "Mod info"
        pageref= "mod-info"
        weight = 4

  [[languages.en.menu.main]]
        identifier = "recipes"
        name = "Cube recipes"
        pageRef= "cube-recipes"
        weight = 5

  [[languages.en.menu.main]]
        identifier = "gm"
        name = "GM"
        url = "/gm-rules"
        pageRef= "gm-rules"
        weight = 6

  [[languages.en.menu.main]]
        identifier = "fpk"
        name = "FPK"
        pageRef= "fpk-rules"
        weight = 7

  [[languages.en.menu.main]]
        identifier = "guides"
        name = "Guides"
        pageRef= "guides/"
        weight = 8
        description = "Diablo 2 Asgard PvP Realm Guides"
        keywords = "diablo guides, d2 guides"

  [[languages.en.menu.main]]
        identifier = "contacts"
        name = "Contacts"
        pageRef= "contacts"
        weight = 9


[languages.ru.menu]
  [[languages.ru.menu.main]]
        identifier = "home"
        name = "Главная"
        pageRef= "/"
        weight = 1
  [[languages.ru.menu.main]]
        identifier = "how"
        name = "Как присоедениться"
        pageRef= "how-to-connect"
        weight = 2

  [[languages.ru.menu.main]]
        identifier = "reg"
        name = "Создать аккаунт"
        pageRef= "create-account"
        weight = 3

  [[languages.ru.menu.main]]
        identifier = "mod"
        name = "Мод"
        pageRef= "mod-info"
        weight = 4

  [[languages.ru.menu.main]]
        identifier = "recipes"
        name = "Рецепты куба"
        pageRef= "cube-recipes"
        weight = 5

  [[languages.ru.menu.main]]
        identifier = "gm"
        name = "ГМ"
        pageRef= "gm-rules"
        weight = 6

  [[languages.ru.menu.main]]
        identifier = "fpk"
        name = "ФПК"
        pageRef= "fpk-rules"
        weight = 7

  [[languages.ru.menu.main]]
        identifier = "guides"
        name = "Гайды"
        pageRef= "guides/"
        weight = 8
        description = "Диабло 2 Асгард ПвП Гайды"
        keywords = "диабло 2 гайды, д2 гайды"

  [[languages.ru.menu.main]]
        identifier = "contacts"
        name = "Контакты"
        pageRef= "contacts"
        weight = 9


