paginate = 20
defaultContentLanguage = 'en'
showLanguageSelector = true
defaultContentLanguageInSubdir = true
baseURL = '/'

[params]
[languages]
[languages.en]
  contentDir = 'content/en'
  languageName = "ENG"
  weight=1
  title = "AsgardPvP"
  subtitle = "International Diablo 2 PvP/Duel server/realm"
  owner = "Progon & Holy"
  keywords = ""
  copyright = ""


[languages.ru]
  contentDir = 'content/ru'
  languageName = "RU"
  weight=2
  title = "АсгардПвП"
  subtitle = "Международный Диабло 2 ПвП сервер"
  owner = "Progon & Holy"
  keywords = ""
  copyright = ""

[languages.en.menu]
  [[languages.en.menu.main]]
        identifier = "Home"
        name = "Home"
        url = "/en/"
        weight = 1

  [[languages.en.menu.main]]
        identifier = "How to connect"
        name = "How to connect"
        url = "/en/how-to-connect"
        weight = 2

  [[languages.en.menu.main]]
        identifier = "Create account"
        name = "Create account"
        url = "/en/create-account"
        weight = 3

  [[languages.en.menu.main]]
        identifier = "Mod info"
        name = "Mod info"
        url = "/en/mod-info"
        weight = 4

  [[languages.en.menu.main]]
        identifier = "Cube recipes"
        name = "Cube recipes"
        url = "/en/cube-recipes"
        weight = 5

  [[languages.en.menu.main]]
        identifier = "GM Rules"
        name = "GM Rules"
        url = "/en/gm-rules"
        weight = 6

  [[languages.en.menu.main]]
        identifier = "FPK Rules"
        name = "FPK Rules"
        url = "/en/fpk-rules"
        weight = 7

  [[languages.en.menu.main]]
        identifier = "Guides"
        name = "Guides"
        url = "/en/guides/"
        weight = 8

  [[languages.en.menu.main]]
        identifier = "Contacts"
        name = "Contacts"
        url = "/en/contacts"
        weight = 9


[languages.ru.menu]
  [[languages.ru.menu.main]]
        identifier = "Главная"
        name = "Главная"
        url = "/ru/"
        weight = 1
  [[languages.ru.menu.main]]
        identifier = "How to connect"
        name = "Как присеоедениться"
        url = "/ru/how-to-connect"
        weight = 2

  [[languages.ru.menu.main]]
        identifier = "Create account"
        name = "Создать аккаунт"
        url = "/ru/create-account"
        weight = 3

  [[languages.ru.menu.main]]
        identifier = "Mod info"
        name = "Мод"
        url = "/ru/mod-info"
        weight = 4

  [[languages.ru.menu.main]]
        identifier = "Cube recipes"
        name = "Рецепты куба"
        url = "/ru/cube-recipes"
        weight = 5

  [[languages.ru.menu.main]]
        identifier = "ГМ правила"
        name = "ГМ правила"
        url = "/ru/gm-rules"
        weight = 6

  [[languages.ru.menu.main]]
        identifier = "ФПК правила"
        name = "ФПК правила"
        url = "/ru/fpk-rules"
        weight = 7

  [[languages.ru.menu.main]]
        identifier = "Guides"
        name = "Гайды"
        url = "/ru/guides/"
        weight = 8

  [[languages.ru.menu.main]]
        identifier = "Contacts"
        name = "Контакты"
        url = "/ru/contacts"
        weight = 9
