paginate = 20
defaultContentLanguage = 'en'
showLanguageSelector = true
defaultContentLanguageInSubdir = false
baseURL = '/'

[params]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[languages]
[languages.en]
  contentDir = 'content/en'
  languageName = "EN"
  weight=1
  title = "AsgardPvP"
  owner = "Progon & Holy"
  description = "Diablo 2 Asgard PvP Realm is an international Diablo 2 PvP arena server designed to play PvP/Duels"
  keywords = "diablo 2 asgard, diablo 2 asgardpvp"
  copyright = "Progon & Holy"

[languages.ru]
  contentDir = 'content/ru'
  languageName = "RU"
  weight=2
  title = "АсгардПвП"
  owner = "Progon & Holy"
  description = "Диабло 2 Асгард ПвП это международный Диабло 2 ПвП сервер"
  keywords = "диабло 2 асгард, диабло 2 асгардпвп"
  copyright = "Progon & Holy"

[languages.en.menu]
  [[languages.en.menu.main]]
        identifier = "Home"
        name = "Home"
        url = "/"
        weight = 1

  [[languages.en.menu.main]]
        identifier = "How to connect"
        name = "How to connect"
        url = "/how-to-connect"
        weight = 2

  [[languages.en.menu.main]]
        identifier = "Create account"
        name = "Create account"
        url = "/create-account"
        weight = 3

  [[languages.en.menu.main]]
        identifier = "Mod info"
        name = "Mod info"
        url = "/mod-info"
        weight = 4

  [[languages.en.menu.main]]
        identifier = "Cube recipes"
        name = "Cube recipes"
        url = "/cube-recipes"
        weight = 5

  [[languages.en.menu.main]]
        identifier = "GM Rules"
        name = "GM Rules"
        url = "/gm-rules"
        weight = 6

  [[languages.en.menu.main]]
        identifier = "FPK Rules"
        name = "FPK Rules"
        url = "/fpk-rules"
        weight = 7

  [[languages.en.menu.main]]
        identifier = "Guides"
        name = "Guides"
        url = "/guides/"
        weight = 8

  [[languages.en.menu.main]]
        identifier = "Contacts"
        name = "Contacts"
        url = "/contacts"
        weight = 9


[languages.ru.menu]
  [[languages.ru.menu.main]]
        identifier = "Главная"
        name = "Главная"
        url = "/ru/"
        weight = 1
  [[languages.ru.menu.main]]
        identifier = "How to connect"
        name = "Как присоедениться"
        url = "/ru/how-to-connect"
        weight = 2

  [[languages.ru.menu.main]]
        identifier = "Create account"
        name = "Создать аккаунт"
        url = "/ru/create-account"
        weight = 3

  [[languages.ru.menu.main]]
        identifier = "Mod info"
        name = "Мод"
        url = "/ru/mod-info"
        weight = 4

  [[languages.ru.menu.main]]
        identifier = "Cube recipes"
        name = "Рецепты"
        url = "/ru/cube-recipes"
        weight = 5

  [[languages.ru.menu.main]]
        identifier = "ГМ правила"
        name = "ГМ правила"
        url = "/ru/gm-rules"
        weight = 6

  [[languages.ru.menu.main]]
        identifier = "ФПК правила"
        name = "ФПК правила"
        url = "/ru/fpk-rules"
        weight = 7

  [[languages.ru.menu.main]]
        identifier = "Guides"
        name = "Гайды"
        url = "/ru/guides/"
        weight = 8

  [[languages.ru.menu.main]]
        identifier = "Contacts"
        name = "Контакты"
        url = "/ru/contacts"
        weight = 9
